name: "Trivy Security Scan and update"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build latest release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          # trivy-config: trivy.yaml
      - name: Trigger rebuild if high vulnerabilities found
        if: failure()
        run: echo "High vulnerabilities found, triggering rebuild..."