name: "Trivy Security Scan and update"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build latest release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Check for vulnerabilities
        id: trivy-scan
        run: |
          trivy fs --severity HIGH --exit-code 1 . || echo "No high vulnerabilities found"

      - name: Trigger rebuild if high vulnerabilities found
        if: failure()
        run: echo "High vulnerabilities found, triggering rebuild..."