name: "Trivy Security Scan and update"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build latest release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.get_latest.outputs.result }}
      
      - name: Check for vulnerabilities
        id: trivy-scan
        run: |
          trivy image --severity HIGH --exit-code 1 ${{ steps.get_latest.outputs.result }} || echo "No high vulnerabilities found"

      - name: Trigger rebuild if high vulnerabilities found
        if: failure()
        run: echo "High vulnerabilities found, triggering rebuild..."