name: "Trivy Security Scan and update"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build latest release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release tag
        id: get_latest
        uses: actions/github-script@v6
        with:
          script: |
            const { github } = require('@actions/github');
            const latestRelease = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return latestRelease.data.tag_name;
            
      - name: Checkout latest release
        run: git checkout ${{ steps.get_latest.outputs.result }}
      
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.get_latest.outputs.result }}
    